### ISSUE TITLE
How do we want this repo to change once the first cycle of the reading group is done?

### ISSUE THREAD

**Issue by dcwalk** [datatogether/reading_datatogether#24]
Are there ways we want to change this repository once the reading group concludes? 

- Do we change it into more of a static site with links into the call notes/calls?
- Does it become more a 'live' coordinating place and we refactor for an ongoing reading group? (i.e., gathering themes, searching out and adding potential readings?
- Are there any ways this could better serve as a resource for us and others stumbling upon this later?

**Comment by dcwalk** [comment]
One thing that would be nice:

- **have a sharable bibliography of all of the things we read!**
  - I started one in #14, which I am happy to keep up to date because it fit my personal flow
  - (however) there are other, and arguably better ways to create and maintain one: [Zotero](https://www.zotero.org/), an open-source "free, easy-to-use tool to help you
collect, organize, cite, and share research"

**Comment by b5** [comment]
To me the bibliography is most important as a near-term goal given you already have a workable PR open 😄, I'd love to see #14 merged

Adding a static site to this repo to make things a little more presentable for others is a _great_ idea IMHO but that'll take a second. If anyone can find time this is a perfect candidate for using existing theme from a favourite static site generator like hugo/jeckyll and add some light DT branding, PR it in and voila!

From there I'd personally commit to putting time into editing the notes & pulling from recordings to synthesize a meeting into content that would more succinctly benefit others. We could use a PR to see if others like the way that shapes up.

**Comment by Mr0grog** [comment]
> Adding a static site to this repo to make things a little more presentable for others is a great idea IMHO but that'll take a second.

I guess I’ll advocate the other side of this one a little bit ;)

Is having a proper website rather than a well-groomed readme and repo (which we certainly should keep on top of) *really* going to add a lot here? Do we need to market this reading group or just provide good access to understandable materials/kits/etc? What are the really valuable things we can do with full HTML, JavaScript, or dynamic forms that add a lot to this resource? GitHub’s markdown rendering can get us pretty far with way less effort (let’s not underestimate how much extra effort someone can pour into a nice web site once they’ve gotten started). Intentionally avoiding making web pages is one of the clever things about “awesome-*” repos, for example.

👍 agree w/ @b5 on the bibs. They are not a thing I’ve ever used much, though (probably to my detriment!), so not sure I have much valuable to say on tools like Zotero.

> I'd personally commit to putting time into editing the notes & pulling from recordings to synthesize a meeting into content that would more succinctly benefit others.

I think this would be great. We should PR just the first meeting to work out a good format, then more people can do the rest in parallel.

> Does it become more a 'live' coordinating place and we refactor for an ongoing reading group? (i.e., gathering themes, searching out and adding potential readings?

I really like this idea. (Actually, I had naïvely assumed this was the plan all along.)

**Comment by dcwalk** [comment]
I should have been more careful with words, by `into more of a static site with links into the call notes/calls` I didn't mean explicitly/only rolling a website, more like how the readme was structured and the presentation of the first cycle of calls/notes

**Comment by lightandluck** [comment]
+1 to synthesizing notes and recordings into condensed content

+1 live coordinating site. Seems like we're continuing the reading group in some form and this repo has already served well in coordinating

+1 giving the repo a little formatting love

I've never used bibtex files, so I feel I would be really bad at keeping that updated, but not opposed to others maintaining that

**Comment by dcwalk** [comment]
Okay, I think this convo and the retrospective helped answer questions around this, in #38 I'm doing a big 2018 clean up which should help set the stage for coordinating 2019.

I'll ping you all for reviews there 😂

**Comment by Frijol** [comment]
Is there more we'd like to work on from this issue as we launch into the 2019 semester?

**Comment by dcwalk** [comment]
It seems like we've moved out actionable items from here. I think probably good to close
