### ISSUE TITLE
Knowledge Commons Readings

### ISSUE THREAD

**Issue by b5** [datatogether/reading_datatogether#40]
@ericnost & @b5 are leading this session, let's assemble some readings! I'm going to start with a pile of stuff to read & will report back on whether it should be included in the coursework. First on my list:

* [ ] **[Future of the commons : beyond market failure and government regulation](https://searchworks.stanford.edu/view/10251006)**
_Elinor Ostrom ; with contributions by Christina Chang, Mark Pennington, Vlad Tarko._

**Comment by ericnost** [comment]
Surfacing "Future threads" from last semester's reading on the Commons:

"Further reading into knowledge commons and follow up topic: building aqueducts and maintaining bridges - knowledge as a commons that requires *maintenance*

- Intro/chapter one from Understanding Knowledge as a Commons [Available [here](http://www.wtf.tw/ref/hess_ostrom_2007.pdf)] <- This seems like required reading. The question is which of the many fascinating-looking chapters. Perhaps Ostrom and Hess "A Framework for Analyzing the Knowledge Commons" ? Or "EconPort: Creating and Maintaining a Knowledge Commons" (given last semester's interest in maintenance)
- Tim Wu "The Master Switch" <- I haven't read this, but I think it would uniquely provide historical context/cases for concentration/centralization in earlier media. 

---

Some other readings I've come across:

- Melanie Dulong de Rosnay, Hervé Le Crosnier. An Introduction to the Digital Commons: From Common-Pool Resources to Community Governance. Tom Dedeurwaerdere. Build- ing Institutions for Sustainable Scientific, Cultural and genetic Resources Commons, Sep 2012, Louvain-la-Neuve, Belgium. International Association for the Study of the Commons, http://biogov.uclouvain.be/iasc/index.php?page=fullpapers, 2012. <- Applies Ostrom's framework to the digital commons
- I have some interest in going back to Hardin's "Tragedy of the Commons." Honestly, that would be more an exercise in critique than anything else. Check out [https://twitter.com/mmildenberger/status/1102604887223750657](this enlightening thread) on Hardin, whom the SPLC has deemed a white nationalist!
- This paper does some comparison between urban/physical forms of common-ing, and digital commons: Bradley, K. Creating, Open-Source Urbanism: Creating, Multiplying and Managing Urban Commons. Commoning as Differentiated Publicness, Spring 2015, pp. 91-108

**Comment by ericnost** [comment]
Hi @b5 - from my list, I'm going to suggest Ostrom and Hess "A Framework for Analyzing the Knowledge Commons" in _Understanding Knowledge as a Commons_ It's pretty conceptual, but with a few examples related to scholarly knowledge/libraries developed throughout. Still, I'm personally really excited about the comparisons with environmental commons (like fisheries, forests, etc.) I haven't seen the Ostrom book you cited above, but this "Framework" chapter might work best because it is specifically on knowledge commons.

From there, I think some chapter from Wu's book would be most engaging, though I don't think it specifically discusses the commons. It seems more about (de)centralization and consolidation. Which is maybe just "enclosure" of the commons, but I don't think he makes that explicit? I haven't read the book. Have you?

The de Rosnay and Le Crosnier article is a more extended application of Ostrom's principles to digital commons more broadly (not just scholarly knowledge commons). So there is some overlap with the "Framework" chapter, but this article has more concrete examples and is more broadly about web commons.

So I would propose Ostrom and Hess, and de Rosnay and Le Crosnier.

**Comment by b5** [comment]
Perfect. I worked through the _future of the commons_ essay/book. It's attempting to build on Ostrom's work in a more "economic angle", and had less to say about knowledge commons than I'd initially hoped. Based on that I think your suggestion of _Understanding Knolwedge as a Commons_ is a far better pick for the "Ostrom contribution" to this conversation. Totally agreed that the comparisons to environmental commons is an important thread in this conversation.

After your note I'm now very excited to dig into the de Rosnay & Le Crosnier article, and think it's a great follow on.

So with that I think we can "ratify" your proposals, and set to work on Wu's book to see how it may apply. I'll start working through the Master switch looking for a compliment to the other two readings. If you'd like to divide & conquer on _The Master Switch_, let me know!

@Frijol, I'm not sure if it's helpful, but we have at least two reading solidified if that helps give others advance notice?

**Comment by ericnost** [comment]
@b5 - sounds good to me! I don't have access to _The Master Switch_ at the moment, but I have requested it from the library. So feel to press on and I will catch up when I get the book.

**Comment by b5** [comment]
Ok, just finished working through enough of _The Master Switch_, and I'm left with the feeling that the work has not aged well. Written in 2011, Wu spends a good amount of time positioning _Google & Facebook as a champions of open_. I think the last few years have cast doubt on that characterization.  I think we're better off focusing on other readings.

With that said, I _really_ enjoyed that twitter thread you linked @ericnost , and the notion of revisiting Hardin's Tragedy of the Commons with a critical eye. I think he poses a question that we could dig in on in relation to Hardin's work:

> We must ask: on what empirical basis do we accept his metaphor? How do we teach his metaphor? Do we contextualize its racist roots? Is it productive to the social transformation necessary to save the world from the climate crisis?

So with that, I wanted to run our "announcement message" by all of you here before posting. I've added both the twitter thread and The Tragedy of the Commons as readings, and would love to know if you agree. One thing that feels like is missing is an introductory paragraph that ties the readings together.

** **
Hi All!

The time has come for the second edition of _Reading Data Together_!  The first topic is **Knowledge Commons**.

When: **Tuesday April 9th @ 5:30pm EST** zoom link to follow.

Readings for this session:

1. Ostrom and Hess "A Framework for Analyzing the Knowledge Commons"
2. Melanie Dulong de Rosnay, Hervé Le Crosnier. An Introduction to the Digital Commons: From Common-Pool Resources to Community Governance. https://halshs.archives-ouvertes.fr/halshs-00736920/document, 2012.
3. This twitter thread from mmildenberger: https://twitter.com/mmildenberger/status/1102604887223750657 
4. Garrett Hardin's "The Tragedy of the Commons"

**Comment by dcwalk** [comment]
Not feeling great about Hardin's Tragedy of the Commons is kind of my jam-- some thoughts,

the Linebaugh reading from last round I think has some specific takes on Hardin: https://github.com/datatogether/reading_datatogether/blob/master/notes/semester_01_2018/3-commons-2018-08-21.md 

Also, there is a nice analysis of Hardin in Commoning as a postcapitalist politics by J.K. Gibson-­Graham, Jenny Cameron, and Stephen Healy (but the Linebaugh one is a little more pointed)

**Comment by ericnost** [comment]
I would love to revisit ToC, especially since I have to teach about it! I'm curious to figure out how to teach it critically. I'm not sure we need to try Linebaugh again right now - let's try something different and maybe shorter (that Twitter thread)? I'd be curious to check out the Gibson-Graham et al. at some point - perhaps we can add it to the longer list of future reads?

I can take a shot later today at writing an introductory paragraph. I think at one level we have three separate projects here: _scaffolding_ our approach to the knowledge commons (i.e. scientific/scholarly resources)(Ostrom and Hess), _applying_ the Ostrom framework to the _digital_ commons more broadly, and _reflecting_ on the "tragedy" of the commons in the first place.

Some more specific questions I'm curious about (and which come up in the readings):
What is the relationship between natural/environmental resources and "immaterial" ones like knowledge and digital resources?
How do we effectively rebut the "tragedy" idea?
(I wasn't able to participate in last year's discussion on commons, so I'm not sure if these cover new/similar ground)

Thanks for taking look at _The Master Switch_ @b5! From the sound of it, it may not be the most effective read. I think we have a great lineup, and good potential future directions (Linebaugh again, Gibson-Graham et al.)

**Comment by b5** [comment]
Ok Just posted to a few channels, mainly because I think these readings need to get out so people can, like, read them. Here's the text I posted:
**  **

Hi All @here!

The time has come for the second edition of *Reading Data Together*!  The first topic is *Knowledge Commons*.

When: *Tuesday April 9th @ 5:30pm EST* zoom link to follow.

Readings for this session:

1. Ostrom and Hess “A Framework for Analyzing the Knowledge Commons”
2. Melanie Dulong de Rosnay, Hervé Le Crosnier. An Introduction to the Digital Commons: From Common-Pool Resources to Community Governance. https://halshs.archives-ouvertes.fr/halshs-00736920/document, 2012.
3. This twitter thread from mmildenberger: https://twitter.com/mmildenberger/status/1102604887223750657
4. Garrett Hardin’s “The Tragedy of the Commons”

We’re hoping these readings will spur us toward frameworks for understanding how open resources beyond nature can be sustainably governed.

If you have any questions feel free to chime in here, or on our planning github issue: https://github.com/datatogether/reading_datatogether/issues/40

:sunny: :tada: YAY FUN LEARNING :dancers: :custard:

**Comment by ericnost** [comment]
Ostrom and Hess are here: http://www.wtf.tw/ref/hess_ostrom_2007.pdf
Hardin is here: http://science.sciencemag.org/content/162/3859/1243/tab-pdf (shouldn't be paywalled...Let me know if otherwise)

**Comment by dcwalk** [comment]
Can we close this now that this session happened? :tada:

**Comment by b5** [comment]
Yesssssssssd
